In [1]:
import numpy as np

In [5]:
layer_dims = [3,4,3,2,1]
parameter={}
for i in range(1,len(layer_dims)):
    parameter['W' + str(i)]=np.random.randn(layer_dims[i],layer_dims[i-1])*0.01
    parameter['b' + str(i)]=np.random.randn(layer_dims[i],1)*0.01
parameter

{'W1': array([[ 0.0066408 , -0.00469469, -0.00267612],
        [ 0.0002536 ,  0.00453229, -0.02661633],
        [-0.00240544, -0.01200377,  0.00810924],
        [-0.01881004, -0.00430121,  0.01472638]]),
 'b1': array([[-0.01128891],
        [-0.00930535],
        [ 0.00715157],
        [-0.0060668 ]]),
 'W2': array([[-0.00030988,  0.0033621 , -0.00269618, -0.01236524],
        [ 0.00606883, -0.00875892, -0.01022125, -0.00194478],
        [ 0.00743314,  0.01310099, -0.00205153, -0.00261474]]),
 'b2': array([[-0.01151168],
        [ 0.01214926],
        [ 0.00177389]]),
 'W3': array([[-0.00091829, -0.00852848, -0.00639432],
        [ 0.00423845,  0.00114655, -0.00370123]]),
 'b3': array([[-0.0259028 ],
        [-0.00571016]]),
 'W4': array([[-0.00090965,  0.0130355 ]]),
 'b4': array([[0.01155425]])}

In [13]:
import numpy as np

a = np.array([[1, 2, 3],[1, 2, 3]])
b = np.array([[4, 5, 6],[6, 7 ,8]])

result = np.dot(a, b.T)

In [16]:
b.T

array([[4, 6],
       [5, 7],
       [6, 8]])

In [23]:
result

array([[32, 44],
       [32, 44]])

In [15]:
result2 = np.multiply(a, b)
result2

array([[ 4, 10, 18],
       [ 6, 14, 24]])

In [17]:
a.shape

(2, 3)

In [18]:
b.shape

(2, 3)

In [19]:
result2.shape

(2, 3)

In [22]:
c = np.array([[1, 2, 3],[4,5,6]])
d = np.array([[5],[6]])
np.multiply(c,d)

array([[ 5, 10, 15],
       [24, 30, 36]])