In [1]:
import numpy as np

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [2]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print('Vectorized version: ' + str(1000*(toc-tic)) +'ms')

249809.18600474377
Vectorized version: 1.0075569152832031ms


In [3]:
c=0

tic = time.time()
for i in range(1000000):
    c += a[i]
toc = time.time()

print(c)
print('For loop: ' + str(1000*(toc-tic)) +'ms')

500106.09528529586
For loop: 203.74274253845215ms


CPU and GPU both have instructions for parallelization instructions, aka SIMD instructions

SIMD = Single Instruction Multiple Data

Avoid using explicit for-loops

In [7]:
# Vectorizing Logistic Regression


In [10]:
# Broadcasting ... Python's expansion of a real variable when working with matrices

A = np.array([[56., 0., 4.4, 68.0],
            [1.2,104.0,52.,8.],
            [1.8,135.,99.,0.9]])

print(A)


[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [11]:
cal = A.sum(axis=-0)
cal

array([ 59. , 239. , 155.4,  76.9])

In [12]:
percentage = A/cal.reshape(1,4)*100
percentage

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

In [13]:
lenth(cal)

NameError: name 'lenth' is not defined