In [1]:
import numpy as np

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [2]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print('Vectorized version: ' + str(1000*(toc-tic)) +'ms')

249809.18600474377
Vectorized version: 1.0075569152832031ms


In [3]:
c=0

tic = time.time()
for i in range(1000000):
    c += a[i]
toc = time.time()

print(c)
print('For loop: ' + str(1000*(toc-tic)) +'ms')

500106.09528529586
For loop: 203.74274253845215ms


CPU and GPU both have instructions for parallelization instructions, aka SIMD instructions

SIMD = Single Instruction Multiple Data

Avoid using explicit for-loops

In [7]:
# Vectorizing Logistic Regression


In [10]:
# Broadcasting ... Python's expansion of a real variable when working with matrices

A = np.array([[56., 0., 4.4, 68.0],
            [1.2,104.0,52.,8.],
            [1.8,135.,99.,0.9]])

print(A)


[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [11]:
cal = A.sum(axis=-0)
cal

array([ 59. , 239. , 155.4,  76.9])

In [12]:
percentage = A/cal.reshape(1,4)*100
percentage

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

In [16]:
A/cal.reshape(1,len(cal))

array([[0.94915254, 0.        , 0.02831403, 0.88426528],
       [0.02033898, 0.43514644, 0.33462033, 0.10403121],
       [0.03050847, 0.56485356, 0.63706564, 0.01170351]])

In [17]:
a = np.random.randn(5)
a

array([-0.2602233 ,  0.29896624,  0.50155245,  1.27332199,  0.15667089])

In [29]:
a.shape
# rank 1 array (5,)

(5, 1)

In [30]:
a.T

array([[ 0.94778184, -0.76570547, -1.01123672,  0.81233053,  1.20824534]])

In [31]:
np.dot(a,a.T)

array([[ 0.89829042, -0.72572174, -0.9584318 ,  0.76991212,  1.14515299],
       [-0.72572174,  0.58630487,  0.77430949, -0.62200593, -0.92516007],
       [-0.9584318 ,  0.77430949,  1.02259971, -0.82145846, -1.22182206],
       [ 0.76991212, -0.62200593, -0.82145846,  0.65988089,  0.98149458],
       [ 1.14515299, -0.92516007, -1.22182206,  0.98149458,  1.45985681]])

In [32]:
a = np.random.randn(5,1)
a
# 1x5 matrix

array([[-0.28000651],
       [ 1.1622665 ],
       [ 0.79436124],
       [-0.680352  ],
       [-0.54310761]])

In [33]:
np.dot(a,a.T)

array([[ 0.07840365, -0.32544219, -0.22242632,  0.19050299,  0.15207367],
       [-0.32544219,  1.35086342,  0.92325946, -0.79075034, -0.63123578],
       [-0.22242632,  0.92325946,  0.63100978, -0.54044526, -0.43142363],
       [ 0.19050299, -0.79075034, -0.54044526,  0.46287885,  0.36950435],
       [ 0.15207367, -0.63123578, -0.43142363,  0.36950435,  0.29496587]])

In [34]:
a = np.random.randn(5,1)
assert(a.shape == (5,1))


In [36]:
np.array([[[1],[2]],[[3],[4]]]).shape

(2, 2, 1)

In [39]:
a = np.array([[1,1],[1,-1]])
b=np.array([[2],[3]])
c=a+b
c

array([[3, 3],
       [4, 2]])

In [40]:
a

array([[ 1,  1],
       [ 1, -1]])

In [41]:
-0.9*log(1)

NameError: name 'log' is not defined